inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.3,7.4],[-0.3,9.],[-0.3,3.]]
  marching_cubes_bound: [[-0.3,7.4],[-0.3,9.],[-0.3,3.]]

grid:
  hash_size: 12 # 0.13

data:
  datadir: /mnt/nas_7/datasets/ScanNet/scans/scene0059_00
  trainskip: 1
  /mnt/nas_8/group/huanggan/Co-SLAM/ScanNet/scene0059_00
  exp_name: demo
