inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-3.6,3.2],[-3.0,5.5],[-1.4,1.7]]
  marching_cubes_bound: [[-3.5,3.1],[-2.9,5.4],[-1.3,1.6]]
  

data:
  datadir: /mnt/nas_8/datasets/Replica/office2
  trainskip: 1
  output: /mnt/nas_8/group/huanggan/Co-SLAM/Replica/office2
  exp_name: demo