inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]
  marching_cubes_bound: [[-1.0,7.0],[-1.3,3.7],[-1.7,1.4]]


data:
  datadir: /mnt/nas_8/datasets/Replica/room0
  trainskip: 1
  output: /mnt/nas_8/group/huanggan/Co-SLAM/Replica/room0
  exp_name: demo